# Generated by Django 3.2 on 2021-04-15 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250, unique=True)),
                ('secret_key', models.CharField(max_length=250, unique=True)),
                ('database_host', models.CharField(max_length=250)),
                ('database_user', models.CharField(max_length=250)),
                ('database_password', models.CharField(max_length=250)),
                ('database_name', models.CharField(max_length=250, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
